/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Canonical frontmatter schema shared by the editor and all builder templates. additionalProperties is false for strict typing — custom fields are still captured by the editor's parser (extractExtra) during content ingestion.
 */
export interface BtsvPostFrontmatter {
  /**
   * Post title. Required.
   */
  title: string;
  /**
   * Original creation datetime as ISO 8601 UTC (e.g. 2026-08-19T14:30:22Z). Set once when the post is first created. Required. Legacy day-precision values (YYYY-MM-DD) remain valid.
   */
  dateCreated: string;
  /**
   * Last modification datetime as ISO 8601 UTC (e.g. 2026-08-19T14:30:22Z). Updated every time the post is saved. Required. Legacy day-precision values (YYYY-MM-DD) remain valid.
   */
  dateUpdated: string;
  /**
   * Publication datetime as ISO 8601 UTC (e.g. 2026-08-19T14:30:22Z). Set once when the post is first published (draft becomes false). Optional — user-editable for backdating. Legacy day-precision values (YYYY-MM-DD) remain valid.
   */
  datePublished?: string;
  /**
   * Short description for SEO, social previews, and post listings.
   */
  description?: string;
  /**
   * List of tags. Generates /tags/<name> listing pages.
   */
  tags?: string[];
  /**
   * If true, the post is excluded from production builds.
   */
  draft?: boolean;
  /**
   * Internal post identifier (timestamp in YYYYMMDD-HHMMSSmm-<rand> format). Auto-generated, do not edit.
   */
  id?: string;
  /**
   * URL slug for the published post. Auto-derived from title. Can be overridden. Required for publishing.
   */
  slug?: string;
  /**
   * If true, marks this entry as a standalone page (About, Contact, etc.) rather than a blog post. Pages are excluded from post listings and RSS.
   */
  page?: boolean;
}
